Repository cloudposse/terraform-yaml-stack-config, pull requests merged in 2021-04, with the labels that each got.

#22 [remote-state] ignore `enabled`, allow `bypass`
  modules/remote-state/main.tf
  modules/remote-state/remote.tf
  modules/remote-state/s3.tf
  modules/remote-state/variables.tf
Labels: no-release

#23 Work around requirement that objects match exactly
  modules/remote-state/main.tf
Labels: bugfix

#26 Fix `imports` output
  .github/workflows/auto-release.yml
  main.tf
Labels: patch
