Repository cloudposse/terraform-yaml-stack-config, pull requests merged in 2024-10, with the labels that each got.

#95 feat: support for gcs backends
  modules/remote-state/data-source.tf
Labels: no-release

#104 Support local backend
  examples/complete/atmos.yaml
  examples/stacks/atmos.yaml
  modules/remote-state/data-source.tf
  modules/remote-state/versions.tf
  test/src/Makefile
  test/src/examples_spacelift_test.go
  test/src/go.mod
  test/src/go.sum
Labels: enhancement, minor, needs-cloudposse

#105 [remote-state] Improve backend compatibility
  modules/remote-state/README.md
  modules/remote-state/data-source.tf
  modules/remote-state/main.tf
Labels: enhancement
